#CloudFormationTemplate Version
#Description

AWSTemplateFormatVersion: '2010-09-09'
Description: 'Cloudformation template for IAM User'

Resources:
  MyIAMUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: 'dyCFN'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AdministratorAccess'

# Create a group - DevGroupCFN
  DevGroupCFN:
    Type: 'AWS::IAM::Group'
    Properties:
      GroupName: 'DevGroupCFN'

# Attach user to group
  UserToGroup:
    Type: 'AWS::IAM::UserToGroupAddition'
    Properties:
      GroupName: !Ref DevGroupCFN
      Users:
        - !Ref MyIAMUser

# IAM Role for EC2 - DevGroupEC2Role
  DevGroupEC2Role:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: ["ec2.amazonaws.com"]
            Action: ['sts:AssumeRole']
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/PowerUserAccess'

# S3 Custom Policy - S3PolicyCFN
  S3PolicyCFN:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: 'S3PolicyCFN'
      PolicyDocument: 
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Action:
              - 's3:GetObject'
            Resource: '*'
      Roles: 
        - !Ref DevGroupEC2Role
