AWSTemplateFormatVersion: '2010-09-09'
Description: 'Cloudformation template for s3 static website'
Resources:
  MyS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties: 
      BucketName: 'dy-s3-bucket-static-website-2026-05-28-2'
      WebsiteConfiguration:
        IndexDocument: 'index.html'
      PublicAccessBlockConfiguration:
        RestrictPublicBuckets: false

  BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref MyS3Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: 'PublicReadGetObject'
            Effect: 'Allow'
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub 'arn:aws:s3:::${MyS3Bucket}/*'
